# Use Alpine as the base image
FROM alpine:latest

# Install required packages
RUN apk add --no-cache shadow bash

RUN addgroup --system --gid 7447 abcd && adduser -rms /bin/sh --uid 7447 --gid 7447 abcd --create-home

RUN mkdir /app
ADD . /app

WORKDIR /app

RUN chmod +x /app/main-entrypoint.sh

USER abcd
ENTRYPOINT ["/app/main-entrypoint.sh"]