# Use Alpine as the base image
FROM alpine:latest

# Install required packages
RUN apk add --no-cache shadow bash

RUN addgroup -g 7447 abcd && \
    adduser -D -u 7447 -G abcd -s /bin/sh abcd

RUN mkdir /app
ADD . /app

WORKDIR /app

RUN chmod +x /app/init-entrypoint.sh

USER abcd
ENTRYPOINT ["/app/init-entrypoint.sh"]